// @flow

// Cart actions
export const CART_FETCH = 'CART_FETCH';
export const CART_RECEIVE = 'CART_RECEIVE';
export const CART_ADD_VARIANT = 'CART_ADD_VARIANT';
export const CART_UPDATE_QUANTITY = 'CART_UPDATE_QUANTITY';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SET_VISIBILITY = 'CART_SET_VISIBILITY';

// Checkout actions
export const CHECKOUT_KLARNA_CREATE_ORDER = 'CHECKOUT_KLARNA_CREATE_ORDER';
export const CHECKOUT_KLARNA_FETCH_ORDER = 'CHECKOUT_KLARNA_FETCH_ORDER';
export const CHECKOUT_KLARNA_RECEIVE_ORDER = 'CHECKOUT_KLARNA_RECEIVE_ORDER';
