

// Cart actions
export const CLIENT_CREATED = 'CLIENT_CREATED';
export const PRODUCTS_FOUND = 'PRODUCTS_FOUND';
export const CHECKOUT_CREATED = 'CHECKOUT_CREATED';
export const CHECKOUT_FOUND = 'CHECKOUT_FOUND';
export const SHOP_FOUND = 'SHOP_FOUND';
export const CART_ADD_VARIANT = 'CART_ADD_VARIANT';
export const CART_UPDATE_QUANTITY = 'CART_UPDATE_QUANTITY';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SET_VISIBILITY = 'CART_SET_VISIBILITY';
